FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    docker.io \
    git \
    python3-pip
RUN python3 -m pip install --upgrade pip
RUN pip3 install pyyaml requests
