FROM ubuntu:noble

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3-dev \
    python3-pip \
    python3-venv \
    libgl1 \
    libglib2.0-0 \
    tzdata
RUN python3 -m venv .test
RUN /bin/bash -c "source .test/bin/activate && python3 -m pip install --upgrade pip"
