FROM amazonlinux

RUN yum install -y \
        python3-pip \
        libgomp \
        mesa-libGL \
        libXi libXcursor libXcomposite libXtst libXScrnSaver libXrandr libXinerama # dependencies for anancoda
RUN python3 -m pip install --upgrade pip
ADD https://repo.anaconda.com/archive/Anaconda3-2021.04-Linux-aarch64.sh /root/anaconda.sh
RUN bash ~/anaconda.sh -b -p $HOME/anaconda
