FROM amazonlinux:2023

RUN yum install -y \
        "@Development tools" \
        python3-devel \
        python3-pip \
        python3-virtualenv \
        libgomp \
        mesa-libGL
RUN python3 -m venv .test
RUN /bin/bash -c "source .test/bin/activate && python3 -m pip install --upgrade pip"
