FROM amazonlinux:2

RUN yum install -y \
        "@Development tools" \
        python3-devel \
        python3-pip \
        libgomp \
        mesa-libGL
ADD https://repo.anaconda.com/archive/Anaconda3-2021.04-Linux-aarch64.sh /root/anaconda.sh
RUN bash ~/anaconda.sh -b -p $HOME/anaconda
RUN python3 -m pip install --upgrade pip
