FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3-pip \
    libgl1 \
    libglib2.0-0
RUN python3 -m pip install --upgrade pip
